install:
  - ps: Write-Host "w/o nprofile"
  - cmd: powershell.exe -encodedCommand ZABpAHIAIAAiAGMAOgBcACoAcAByAG8AagAqACIAIAA=
  - ps: Write-Host "with nprofile"
  - cmd: powershell.exe -noprofile -encodedCommand ZABpAHIAIAAiAGMAOgBcACoAcAByAG8AagAqACIAIAA=

build: off
test: off
deploy: off

#on_finsih:
 # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
