version: 1.0.{build}
build: off
artifacts:
- path: src\VeryNewWebJob
  name: VeryNewWebJob
deploy:
- provider: AzureWebJob
  website: ilyaf
  username: ilyafdepl
  password:
    secure: JqjMdWRH22nh8HpJCv3zVQ==
  artifact: VeryNewWebJob
  continuous: true
  triggered: false
  job_schedule: '*0****'
