version: 1.0.22.{build}
image: Visual Studio 2015
clone_folder: $(HOMEDRIVE)$(HOMEPATH)\go\src\site\org\project
init:
- ps: >-
    write-host "waiting for debugger"

    start-sleep 40
environment:
  GOPATH: $(HOMEDRIVE)$(HOMEPATH)\go
build:
  project: src\ProjectA.sln
  verbosity: minimal
