install:
  - set TEST_VAR=Hello, world!
  - echo before reboot
  - ps: Restart-Computer -Force      # here the server goes restarting
  - ps: Start-Sleep -s 10

build_script:
  - echo after reboot
  - echo %TEST_VAR%

test: off
deploy: off
