-
    version: 2.0.0.{build}-{branch}
  
    branches:
      only:
        - master
        - develop
    
    install:
    - ps: 'Write-host "Top config. Branch: "$env:APPVEYOR_REPO_BRANCH'
    
    build: off

-
    version: 2.0.0.{build}-{branch}

    install:
    - ps: 'Write-host "Bottom config. Branch: "$env:APPVEYOR_REPO_BRANCH'
    
    build: off
