version: 2.0.0.{build}-{branch}
image: Visual Studio 2015

init:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#install:
# - ps: Add-AppveyorMessage "Hello message"

build:
  project: src\ProjectA.sln
  verbosity: minimal
