-
    version: 2.0.0.{build}-{branch}
  
    branches:
      only:
        - master

    build:
      project: src\ProjectA.sln
      publish_nuget: true
      verbosity: minimal  

-
    version: 2.0.0.{build}-{branch}

    build:
      project: src\ProjectA.sln
      publish_nuget: false
      verbosity: minimal  
