environment:
  global: 
    my_var:
      secure: PDuDFXR97swbDu9DWD4+ww==
build_script:
- 'appveyor downloadfile "https://ci.appveyor.com/api/projects/analogdevicesinc/scopy-mingw-build-deps/artifacts/scopy-mingw32-build-deps.tar.xz?branch=master&job=Environment: MINGW_VERSION=mingw32, ARCH=i686" -FIleName bla.zip'

notifications:
    - provider: Email
      to:
        - ilya_f@hotmail.com
      on_build_success: true
      on_build_failure: true
