version: 1.0.{build}
artifacts:
- path: src\VeryNewWebJob
  name: VeryNewWebJob
build: off
deploy:
- provider: AzureWebJob
  website: ilyaf
  username: ilyafdepl
  password:
    secure: JqjMdWRH22nh8HpJCv3zVQ==
  artifact: VeryNewWebJob
  manually_triggered: false
  job_schedule: '*0****'
