version: 1.0.real.{build}
image: Visual Studio 2015
init:
- ps: Write-host "Starting sleep..."
- ps: Start-sleep 30
before_build:
- cmd: >-
    echo %cd%
    
    echo %APPVEYOR_BUILD_FOLDER%
    
    dir
    
    cd src
    
    echo %cd%
    
build:
  # Relative path to solutions file - passed
  #project: src\ProjectA.sln
  
  # Relative path folder with solutions file - passed
  #project: src
  
  # Relative path to solutions file - passed
  project: src\ProjectA\ProjectA.csproj
  
  # Relative path folder with project file - passed
  #project: src\ProjectA
  
  verbosity: minimal
deploy: off
