version: 1.0.{build}
image: Visual Studio 2015
build:
  verbosity: minimal
artifacts:
- path: ProjectA
  name: ProjectAe
- path: ProjectA\deploy.ps1
  name: deployps1e
- path: ProjectA\bin\Debug\ProjectA.dll
  name: ProjectAdll
  
init:
- ps: Write-host $env:TSD_GITHUB_TOKEN
environment:
  TSD_GITHUB_TOKEN:
    secure: 3o+i2d6yzGSu4/Kv/+PDRXNJb2R0wVtjjqhuzmpu+kRmRGYM9Ph3+ppLbT2sLmSM