-
  branches:
    only:
      - master*

  configuration: Release

  build:
      project: src\ProjectA.sln
      verbosity: minimal

-
  branches:
    only:
      - dev*

  configuration: Debug

  build:
      project: src\ProjectA.sln
      verbosity: minimal
