version: "policies-{branch}-{build}"

environment:
  cert_key:
    secure:
  cert_pw_key:
    secure:
  image: Visual Studio 2015
  fast_finish: true
  RUBY_VERSION: 23
  #matrix:
    #- RUBY_VERSION: 21
    #- RUBY_VERSION: 21-x64
    #- RUBY_VERSION: 22
    #- RUBY_VERSION: 22-x64
    #- RUBY_VERSION: 23
    #- RUBY_VERSION: 23-x64

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  # Set up our PATH
  - set PATH="C:\Ruby%RUBY_VERSION%\bin";"C:\Program Files\Git\mingw64\bin";C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;"C:\Program Files (x86)\Inno Setup 5";%PATH%
  # Install InnoSetup
  - choco install -y InnoSetup
  # This decrypts cert/cert password
  - nuget install secure-file -ExcludeVersion
  # Install Ruby Dependencies
  - gem install bundler
  - gem install mime-types-data -v '3.2016.0521'
  - bundle install
  - gem env

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - bundle show rspec
  - echo %PATH%
  - which rspec
  - dir c:\Ruby23\bin\rsp*
  - where rspec*

test_script:
  - bundle exec rspec --color --pattern test\integration\default\serverspec\*\*_spec.rb

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # - provider: Email
    # to:
      # - kevin.pickard@jumpcloud.com
    # subject: 'Build {{status}}'
    # message: "{{message}}, {{commitId}}, Completed"
    # on_build_status_changed: true
