version: 2.0.0.{build}-{branch}
image: Visual Studio 2015


environment: 
  matrix: 
    - configuration: Debug
      #platform: x64
      
    - configuration: Release
      #platform: x64 

build:
  project: src\ProjectA.sln
  verbosity: minimal
