version: 1.0.real.{build}
image: Visual Studio 2015

install:
- ps: |
    
    Install-WindowsFeature -Name DNS -IncludeManagementTools
    
    Install-WindowsFeature -Name DHCP -IncludeManagementTools
    
    Add-DnsServerPrimaryZone -Name foo.bar -ZoneFile foo.bar.dns
    
    Add-DhcpServerv4Scope -Name TestScope -StartRange 192.168.1.100 -EndRange 192.168.1.110 -SubnetMask 255.255.255.0
    
    $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {$_.InterfaceAlias -like '*ethernet*'}).IPAddress
    
    Set-DHCPServerv4OptionValue -DnsDomain foo.bar -DnsServer $ip
    
    $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
build: off

#   powershell -NoProfile -encodedCommand JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQA7ACAAdwByAGkAdABlAC0AaABvAHMAdAAgACcAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAIABoAGEAcwAgAGQAZQBmAGEAdQBsAHQAIABzAGUAdAB0AGkAbgBnAHMAJwA=

 #   powershell -NoProfile -encodedCommand JABQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQA9ACcAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnADsAIAAkAFAAcgBvAGcAcgBlAHMAcwBQAHIAZQBmAGUAcgBlAG4AYwBlADsAIAB3AHIAaQB0AGUALQBoAG8AcwB0ACAAJwBQAHIAbwBnAHIAZQBzAHMAUAByAGUAZgBlAHIAZQBuAGMAZQAgAGkAcwAgAHMAZQB0ACAAdABvACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAnAA==
 

# init:
# - ps: Write-host "Starting sleep, look process ID, attach debugger..."
# - ps: Start-sleep 30

# before_build:
# #intentionally changing current dir level down
# - cmd: cd src
# - cmd: echo %cd%
    
# >>>>>>> origin/master
# build:
  # # Relative path to solutions file - passed
  # #project: src\ProjectA.sln
  
  # # Relative path folder with solutions file - passed
  # #project: src
  
  # # Relative path to solutions file - passed
  # # project: src\ProjectA\ProjectA.csproj
  
  # # Relative path folder with project file - passed
  # #project: src\ProjectA
  
  # # Check if it will regress for somebody who set absolute path
  # project: c:\projects2\projecta-iasutr5hs65tagxt\src\ProjectA\ProjectA.csproj
  
  # verbosity: minimal
# # artifacts:
# # - path: ProjectA
  # # name: ProjectA
# deploy: off
