version: 1.0.real.{build}
image: Visual Studio 2015

build: off
install:
  - ps: [System.IO.File]::WriteAllText(".\version.txt", $env:APPVEYOR_REPO_COMMIT)
#artifacts:
# - path: version.txt
#    name: version

