-
  branches:
    only:
      - master

  configuration: Release
  skip_tags: true

  build:
      project: src\ProjectA.sln
      verbosity: minimal

-
  branches:
    only:
      - dev

  configuration: Debug
  deploy: 

  build:
      project: src\ProjectA.sln
      verbosity: minimal
