version: 1.0.{build}
image: Visual Studio 2015
before_build:
- ps: Write-host $env:TSD_GITHUB_TOKEN
build:
  verbosity: minimal
artifacts:
- path: ProjectA
  name: ProjectA
- path: ProjectA\deploy.ps1
  name: deployps1
- path: ProjectA\bin\Debug\ProjectA.dll
  name: ProjectAdll
 environment:
  TSD_GITHUB_TOKEN:
    secure: 3o+i2d6yzGSu4/Kv/+PDRXNJb2R0wVtjjqhuzmpu+kRmRGYM9Ph3+ppLbT2sLmSM